<?php
// $Id$

/**
 * @file Gettext translation template extractor.
 */

/**
 * Implementation of hook_help().
 */
function potx_help($section) {
  switch ($section) {
    case 'admin/help#potx':
    case 'admin/modules#description':
      return t('Helps to extract pot-files for translations from the sources of installed modules.');
    case 'admin/settings/locale/potx':
      return t('This page allows you to generate translation templates for module files. Select the module you wish to generate a template file for. A single Gettext Portable Object Template file is generated (unlike the output of the command line extractor utility), so you can easily save it and start translation.');
  }
}

/**
 * Implementation of hook_menu().
 */
function potx_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array(
      'path' => 'admin/settings/locale/potx',
      'title' => t('Extract strings'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('potx_select_form'),
      'access' => user_access('administer locales'),
      'weight' => 20,
      'type' => MENU_LOCAL_TASK,
    );
  }
  return $items;
}

/**
 * Module selection interface.
 * 
 * @todo
 *   Look into correct PO generation, commented for now.
 */
function potx_select_form() {

  $form = array();
  $modules = _potx_module_list();
  _potx_build_module_form($form, $modules);

  /*
  // Generate translation file for a specific language if possible.
  $supported = locale_supported_languages();
  $names = $supported['name'];
  if (count($names) > 1) {
    $options = array('pot' => t('Translation template file'));
    foreach ($names as $langcode => $name) {
      // Skip English for PO generation.
      if ($langcode == 'en') {
        continue;
      }
      $options[$langcode] = t('Translation file for !langname', array('!langname' => $name));
    }
    $form['type'] = array(
      '#type' => 'radios',
      '#title' => t('Extract type'),
      '#default_value' => 'pot',
      '#options' => $options,
      '#description' => t('Choose to create a pot-file or a po-file filled with drupal-translations'),
    );
  }*/

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Extract'),
  );

  return $form;
}

/**
 * Generate translation templates for the requested module.
 */
function potx_select_form_submit($form_id, &$form) {

  // This could take some time.
  @set_time_limit(0);
  require_once('potx.inc');

  // Silence status messages.
  _potx_status(POTX_STATUS_SILENT);

  // $form['module'] either contains a specific module file name
  // with path, or a directory name for a module or a module suite.
  // Examples:
  //   modules/watchdog
  //   sites/all/modules/potx
  //   sites/all/modules/i18n/i18n.module
  
  $pathinfo = pathinfo($form['module']);
  
  // A specific module file was requested.
  if ($pathinfo['extension'] == 'module') {
    $filename = basename($pathinfo['basename'], '.module');
    $files = _potx_explore_dir($pathinfo['dirname'] . '/', $filename);
    $outputname = $filename . '.pot';
  }
  // A directory name was requested.
  else {
    $files = _potx_explore_dir($form['module'] . '/');
    $outputname = $pathinfo['basename'] . '.pot';
  }
  
  /*
  // Template or translation file generation.
  $langcode = NULL;
  if (isset($form['type']) && ($form['type'] != 'pot')) {
    $langcode = $form['type'];
    $httpout .= ".$langcode.po";
  }
  else {
    $httpout .= '.pot';
  }
  */

  // Collect every string in affected files. Installer related strings are discared.
  $strings = $file_versions = $installer_strings = array();
  foreach ($files as $file) {
    _potx_process_file($file, $strings, $file_versions, $installer_strings);
  }
  _potx_build_files($strings, $file_versions);
  _potx_write_files($outputname);

  exit;
}

/**
 * Build a chunk of the module selection form.
 *
 * @param $form
 *   Form to populate with fields.
 * @param $modules
 *   Structured array with modules as returned by _potx_module_list().
 * @param $dirname
 *   Name of directory handled.
 */
function _potx_build_module_form(&$form, &$modules, $dirname = '') {

  // Pop off count of modules in this directory.
  if (isset($modules['.modulecount'])) {
    $modules_in_dir = $modules['.modulecount'];
    unset($modules['.modulecount']);
  }

  ksort($modules);
  $dirkeys = array_keys($modules);
  
  // A directory with one module.
  if ($modules_in_dir && (count($modules) == 1)) { 
    $module_dir = dirname($modules[$dirkeys[0]]->filename);
    $form[_potx_form_id('dir', $module_dir)] = array(
      '#type' => 'radio',
      '#title' => t('Extract from %module_name module, in directory %dir_name', array('%dir_name' => $module_dir, '%module_name' => basename($modules[$dirkeys[0]]->basename, '.module'))),
      '#description' => t('Generates output from all files found in this directory.'),
      '#default_value' => 0,
      '#return_value' => $module_dir,
      // Get all radio buttons into the same group.
      '#parents' => array('module'),
    );
    return;
  }

  // A directory with multiple modules in it.
  if (preg_match('!/modules\\b(/.+)?!', $dirname, $pathmatch)) {
    $subst = array('%dir_name' => substr($dirname, 1));
    if ($pathmatch[1]) {
      $form[_potx_form_id('dir', $dirname)] = array(
        '#type' => 'radio',
        '#title' => t('Extract from all modules in directory %dir_name', $subst),
        '#description' => t('To extract from a single module in this directory, choose the module entry in the fieldset below.'),
        '#default_value' => 0,
        '#return_value' => substr($dirname, 1),
        // Get all radio buttons into the same group.
        '#parents' => array('module'),
      );
    }
    $element = array(
      '#type' => 'fieldset',
      '#title' => t('Modules in %dir_name', $subst),
      '#collapsible' => true,
      '#collapsed' => true,
    );
    $form[_potx_form_id('fs', $dirname)] =& $element;
  }
  else {
    $element =& $form;
  }

  foreach ($dirkeys as $entry) {
    // A module in this directory with multiple modules.
    if ($entry[0] == '#') {
      $subst = array(
        '%module_dir' => dirname($modules[$entry]->filename),
        '%module_name' => basename($modules[$entry]->basename, '.module'),
        '%module_pattern' => basename($modules[$entry]->basename, '.module'). '.*',
      );
      $element[_potx_form_id('mod', $modules[$entry]->basename)] = array(
        '#type' => 'radio',
        '#title' => t('Extract from module %module_name', $subst),
        '#description' => t('Extract from files named %module_pattern, in directory %module_dir.', $subst),
        '#default_value' => 0,
        '#return_value' => $modules[$entry]->filename,
        // Get all radio buttons into the same group.
        '#parents' => array('module'),
      );
    }
    // A subdirectory we need to look into.
    else {
      _potx_build_module_form($element, $modules[$entry], "$dirname/$entry");
    }
  }

  return count($modules);
}

/**
 * Generate a sane form element ID for the current radio button.
 *
 * @param $type
 *   Type of ID generated: 'fs' for fieldset, 'dir' for directory, 'mod' for module
 * @param $path
 *   Path of file we generate an ID for.
 * @return
 *   The generated ID.
 */
function _potx_form_id($type, $path) {
  return "potx-$type-" . preg_replace('/[^a-zA-Z0-9]+/', '-', $path);
}

/**
 * Generate a hierarchical structured list of modules.
 */
function _potx_module_list() {
  // Get current list of enabled modules and their file names.
  $files = drupal_system_listing('\.module$', 'modules', 'name', 0);
  system_get_files_database($files, 'module');
  ksort($files);

  $modules = array();
  foreach ($files as $file) {
    // Skip disabled modules
    if ($file->status != 1) {
      continue;
    }
    
    // Build directory tree structure.
    $path_parts = explode('/', dirname($file->filename));
    $dir =& $modules;
    foreach ($path_parts as $dirname) {
      if (!isset($dir[$dirname])) {
        $dir[$dirname] = array();
      }
      $dir =& $dir[$dirname];
    }

    // Information about modules in this directory.
    $dir['#'.$file->basename] = $file;
    $dir['.modulecount'] = isset($dir['.modulecount']) ? $dir['.modulecount'] + 1 : 1;
  }

  return $modules;
}
