<?php

/**
 * @file
 *   File used purely to test the parser in potx.
 */

/**
 * Doing something amazing. Don't really care for all the details of
 * annotations really.
 *
 * @Translation("Good translation annotation")
 * @Translation("Translation in good context", context="Translation test")
 */
function potx_test_8_example() {
}

/**
 * Doing something amazing. Don't really care for all the details of
 * annotations really, but we catch errors.
 *
 * @Translation("Bad translation annotation)
 * @Translation(Worse translation annotation)
 * @Translation("Another good translation annotation")
 * @Translation Even worse
 * @Translation("Final good translation annotation")
 */
function potx_test_8_sample() {
}

/**
 * Empty annotations are not allowed either.
 *
 * @Translation("")
 */
function potx_test_8_empty() {
}
